name: Qt MacOS

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: ZFModuleDemo_app/zfproj
      ZF_PROJ_NAME: ZFModuleDemo_app

    steps:
    - uses: actions/checkout@v3

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        host: mac
        target: desktop
        modules: qtwebengine qtwebchannel qtpositioning
        version: 6.5.3 # https://bugreports.qt.io/browse/QTBUG-117225

    - name: ZFSetup
      run: |
        chmod +x ./zfsetup.sh
        ./zfsetup.sh

    - name: ZF build zfproj
      run: |
        chmod +x ../ZFFramework/tools/buildapp/buildapp_Qt_MacOS.sh
        ../ZFFramework/tools/buildapp/buildapp_Qt_MacOS.sh "${ZF_PROJ_NAME}" "${ZF_PROJ_PATH}"

