name: Qt Windows with src

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: ZFModuleDemo_app/zfproj
      ZF_PROJ_NAME: ZFModuleDemo_app

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSVC cmd
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        export-path-to-vcvarsall: VCVARSALL_PATH
        arch: x64

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        host: windows
        target: desktop
        modules: qtwebengine

    - name: ZFSetup
      run: |
        Invoke-Expression -Command 'cmd.exe /C ".\\zfsetup.bat"'

    - name: ZF build zfproj
      run: |
        Invoke-Expression -Command 'cmd.exe /C "..\\ZFFramework\\tools\\buildapp\\buildapp_Qt_Windows.bat" "$env:ZF_PROJ_NAME" "$env:ZF_PROJ_PATH"'

